//Repetitions identifier

#include  <stdio.h>
#include  <stdlib.h>
#include  <string.h>

int main()
{
    
//Made Simple extract    
//char *cip="UTPDHUGNYHUSVKCGMVCEFXLKQIBWXRKUGITZNRLSBBHZLXMSNPKDKSCEBIHHKEWIBAYYMSBRPFRSBSJVUPLOUVADGRHRRWXFJVZTVOOVYHZCQUYUKWGEBPLUQFBPFOUKCGTBFRQVHCFRKPGOUKFTZCQUMAWQKKWZGSYFPPGMQKFTKUQFBDEREZRNMCYEMGUCTFSVAWPKFTZCQUMAWKQIJSLCOVNTHDNVJPNUJVBIHGGVRWXONKCGTHKFLXGVKDZJMVGCCIMVGDJPNUJRLSEWVKJTASGUCSMVGDDDKVGNYHPWUVCCHIIYRDDBQNRWTHPFRWBBIVTTKVCGNTGSFFLIAWUXJDUSHFPVHCFRRLAWEYQDFSRVMEESFZBCHHJRTTMVGZPUBZNFDATIIYRTKWPKFTHIVJCITBFBLDPWPXRWTHULAWTGVYCHXKQLJSUSDCGCWOPPUPRVGKFDNUJKGIJIKKCPLKGCJIAOVKFTRGJFSAWKTZLZESWGRWXWTVWTLWPXPXGGCJFPOSVYCBTZCUWXGZGJQPMHTRAIBJGWMGFGJZQDPBJVYGMZCLEWXRCEBIAOVNYHJIKKCTGCWXFUHFJZKWXVCULDYITKFTKWPKCGVCWIQTPWVYQEBFKKQQNHNZTTWIRFLIASVFRPEODJRXGSPTCEKWPTGEESGMCGTTVVPLTFFJYCWWVNYHTZYRWHLOKUMUAWOKFPMVGBLTPVQNRDDSGGAWKWUKKPLKGCJXYOPPKPGONZTTICUJCHLSFKFTDBQNJTWUGDYNMVCKZTMFWCWHTWFFDJLOPUYAECHLQ!PGRUFYHMWPPRXFCDJCGOSFXMSUZGJQJLSXVPNHBG";

//Vigenere Encryption and Kasiski video extract
//char *cip = "UYEBVGMPFXAVUUAETPARWJCKHMUTBGUUAETPARWQKWECAPQNXLGMZGFPWTBCEGFZTGULUAIPPGOBTNNCZXITP";

//TRIGRAM SEARCH
    
    
    /*
    int l = 0;
    int d = 0;
    for (int i = 0; i < strlen(cip); i++)
    {
        if (l == 3){d++; i -= 2; l = 0;}
        l++;
    }
    printf ("%d", d);
    //d is all possible 3 combos
    */
    
   // triArray[3][d]
   // occurances[d]
   
    
   // occurances[2] = 4 
  //means that the second trigram occurred 4 times
    

    
    
 
    
}
